import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/sheare/navber";
import Footer from "@/components/sheare/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` max-w-screen-2xl mx-auto ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar/>
        {children}

        <Footer/>
      </body>
    </html>
  );
}
